import { launchChrome } from './browser.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';

await fs.mkdir('docs/evidence', { recursive: true });
const browser = await launchChrome();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /enter the garage/i }).click();
await page.getByRole('button', { name: /design your panel art/i }).click();
await page.getByText('Draw', { exact: true }).click();
await page.locator('[data-testid="native-draw-size"]').fill('35');
const canvas = await page.locator('canvas.upper-canvas').boundingBox();
const x = canvas.x, y = canvas.y;
await page.mouse.move(x + 650, y + 220);
await page.mouse.down();
await page.mouse.move(x + 790, y + 350, { steps: 24 });
await page.mouse.up();
await page.screenshot({ path: 'docs/evidence/editor-edited.png', fullPage: true });
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.getByText('ARTWORK APPLIED').waitFor({ timeout: 15000 });
await page.screenshot({ path: 'docs/evidence/applied-desktop.png', fullPage: true });
console.log('APPLIED:', await page.getByText('ARTWORK APPLIED').count());
await page.getByRole('button', { name: /roll out/i }).click();
await page.getByRole('button', { name: /skip reveal/i }).click();
await page.screenshot({ path: 'docs/evidence/cover-preview-desktop.png', fullPage: true });
const coverDownload = page.waitForEvent('download');
await page.getByRole('button', { name: /save cover/i }).click();
const cover = await coverDownload;
await cover.saveAs('docs/evidence/sample-cover.png');
const artDownload = page.waitForEvent('download');
await page.getByRole('button', { name: /save flat art/i }).click();
const art = await artDownload;
await art.saveAs('docs/evidence/sample-panel-art.png');
const coverBytes = await fs.readFile('docs/evidence/sample-cover.png');
assert.equal(coverBytes.readUInt32BE(16), 1600);
assert.equal(coverBytes.readUInt32BE(20), 2000);
const artBytes = await fs.readFile('docs/evidence/sample-panel-art.png');
assert.ok(artBytes.length > 10000);
await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('button', { name: /enter the garage/i }).click();
await page.getByText('ARTWORK APPLIED').waitFor({ timeout: 10000 });
const afterPixels = await page.locator('.garage-stage canvas').evaluate(el => el.toDataURL());
await page.getByRole('button', { name: /before \/ after/i }).click();
const beforePixels = await page.locator('.garage-stage canvas').evaluate(el => el.toDataURL());
assert.notEqual(afterPixels, beforePixels, 'before/after should visibly change the vehicle');
await page.getByRole('button', { name: /show after/i }).click();
await page.getByRole('button', { name: /edit applied art/i }).click();
await page.getByRole('button', { name: 'Save', exact: true }).waitFor();
await page.getByRole('button', { name: /back to garage/i }).click();
await page.getByText('ARTWORK APPLIED').waitFor();
console.log('DOWNLOADS:', cover.suggestedFilename(), art.suggestedFilename());
console.log('RESTORE / BEFORE-AFTER / CANCEL: passed');
console.log('ERRORS:', errors);
await browser.close();
