import { launchChrome } from './browser.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';

await fs.mkdir('docs/evidence', { recursive: true });
const browser = await launchChrome();
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, acceptDownloads: true });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto(process.env.VICECHROME_URL || 'http://localhost:5173/', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'docs/evidence/welcome-mobile.png', fullPage: true });
await page.getByRole('button', { name: /enter the garage/i }).click();
await page.waitForTimeout(600);
const before = await page.locator('.garage-stage canvas').evaluate(el => el.toDataURL());
await page.screenshot({ path: 'docs/evidence/garage-mobile.png', fullPage: true });
await page.getByRole('button', { name: /design your panel art/i }).click();
await page.waitForFunction(() => !document.querySelector('.mobile-editor-actions button:last-child')?.hasAttribute('disabled'), { timeout: 30000 });
await page.screenshot({ path: 'docs/evidence/editor-mobile.png' });
assert.ok(await page.getByRole('button', { name: /save artwork/i }).isVisible());
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.getByText('Text', { exact: true }).click();
await page.locator('.editor-frame').evaluate(el => { el.scrollLeft = 0; });
assert.ok((await page.locator('canvas.upper-canvas').boundingBox()).width > 300);
assert.ok(await page.getByRole('button', { name: /save artwork/i }).isVisible());
await page.getByText('Draw', { exact: true }).click();
await page.locator('.editor-frame').evaluate(el => { el.scrollLeft = 0; });
const canvas = await page.locator('canvas.upper-canvas').boundingBox();
await page.screenshot({ path: 'docs/evidence/editor-mobile-draw-open.png' });
assert.ok(canvas.width > 300 && canvas.height > 400);
await page.mouse.move(canvas.x + canvas.width * .58, canvas.y + canvas.height * .47);
await page.mouse.down();
await page.mouse.move(canvas.x + canvas.width * .83, canvas.y + canvas.height * .56, { steps: 18 });
await page.mouse.up();
await page.screenshot({ path: 'docs/evidence/editor-mobile-edited.png' });
await page.getByRole('button', { name: /save artwork/i }).click();
await page.getByText('ARTWORK APPLIED').waitFor({ timeout: 10000 });
const after = await page.locator('.garage-stage canvas').evaluate(el => el.toDataURL());
assert.notEqual(after, before, 'mobile edit must change the applied car');
await page.screenshot({ path: 'docs/evidence/applied-mobile.png', fullPage: true });
await page.getByRole('button', { name: /roll out/i }).click();
await page.getByRole('button', { name: /skip reveal/i }).click();
const download = page.waitForEvent('download');
await page.getByRole('button', { name: /save cover/i }).click();
const cover = await download;
await cover.saveAs('docs/evidence/mobile-cover.png');
const bytes = await fs.readFile('docs/evidence/mobile-cover.png');
assert.equal(bytes.readUInt32BE(16), 1600);
assert.equal(bytes.readUInt32BE(20), 2000);
const changedPixels = await page.evaluate(async encoded => {
  const { makeStarter } = await import('/src/art.ts');
  const { renderCover } = await import('/src/render.ts');
  const image = new Image(); image.src = `data:image/png;base64,${encoded}`; await image.decode();
  const starter = new Image(); starter.src = makeStarter('sunset'); await starter.decode();
  const baseline = document.createElement('canvas');
  renderCover(baseline.getContext('2d'), { art: starter, scene: 'boulevard', paint: 'graphite' }, 'SUNSET COURIER');
  const coverCanvas = document.createElement('canvas'); coverCanvas.width = 1600; coverCanvas.height = 2000;
  coverCanvas.getContext('2d').drawImage(image, 0, 0);
  const a = coverCanvas.getContext('2d').getImageData(550, 1000, 480, 155).data;
  const b = baseline.getContext('2d').getImageData(550, 1000, 480, 155).data;
  let changed = 0;
  for (let i = 0; i < a.length; i += 4) if (Math.abs(a[i] - b[i]) + Math.abs(a[i + 1] - b[i + 1]) + Math.abs(a[i + 2] - b[i + 2]) > 80) changed++;
  return changed;
}, bytes.toString('base64'));
assert.ok(changedPixels > 100, `mobile edit should appear on cover; changed pixels: ${changedPixels}`);
assert.deepEqual(errors, []);
console.log('Mobile Draw, Save, applied car, and cover export passed.');
await browser.close();
