import { launchChrome } from './browser.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';

await fs.mkdir('docs/evidence', { recursive: true });
const browser = await launchChrome();
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, acceptDownloads: true });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto(process.env.VICECHROME_URL || 'http://localhost:5173/', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'docs/evidence/welcome-mobile.png', fullPage: true });
await page.getByRole('button', { name: /enter the garage/i }).click();
await page.waitForTimeout(600);
const before = await page.locator('.garage-stage canvas').evaluate(el => el.toDataURL());
await page.screenshot({ path: 'docs/evidence/garage-mobile.png', fullPage: true });
await page.getByRole('button', { name: /design your panel art/i }).click();
await page.waitForFunction(() => !document.querySelector('.mobile-editor-actions button:last-child')?.hasAttribute('disabled'), { timeout: 30000 });
await page.screenshot({ path: 'docs/evidence/editor-mobile.png' });
assert.ok(await page.getByRole('button', { name: /save artwork/i }).isVisible());
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.getByText('Text', { exact: true }).click();
await page.locator('.editor-frame').evaluate(el => { el.scrollLeft = 0; });
const textLayout = await page.evaluate(() => ({ frame: document.querySelector('.editor-frame').getBoundingClientRect().toJSON(), canvas: document.querySelector('canvas.upper-canvas').getBoundingClientRect().toJSON() }));
assert.ok(textLayout.canvas.width > 300 && textLayout.canvas.height > 300);
assert.ok(textLayout.canvas.bottom <= textLayout.frame.bottom + 1);
assert.ok(await page.getByRole('button', { name: /save artwork/i }).isVisible());
await page.getByText('Draw', { exact: true }).click();
await page.locator('.editor-frame').evaluate(el => { el.scrollLeft = 0; });
const canvas = await page.locator('canvas.upper-canvas').boundingBox();
await page.screenshot({ path: 'docs/evidence/editor-mobile-draw-open.png' });
assert.ok(canvas.width > 300 && canvas.height > 400);
await page.mouse.move(canvas.x + canvas.width * .58, canvas.y + canvas.height * .47);
await page.mouse.down();
await page.mouse.move(canvas.x + canvas.width * .83, canvas.y + canvas.height * .56, { steps: 18 });
await page.mouse.up();
await page.screenshot({ path: 'docs/evidence/editor-mobile-edited.png' });
await page.getByRole('button', { name: /save artwork/i }).click();
await page.getByText('ARTWORK APPLIED').waitFor({ timeout: 10000 });
await page.screenshot({ path: 'docs/evidence/applied-mobile.png', fullPage: true });
const after = await page.locator('.garage-stage canvas').evaluate(el => el.toDataURL());
assert.notEqual(after, before, 'mobile edit must change the applied car');
await page.getByRole('button', { name: /roll out/i }).click();
await page.getByRole('button', { name: /skip reveal/i }).click();
const download = page.waitForEvent('download');
await page.getByRole('button', { name: /save cover/i }).click();
const cover = await download;
await cover.saveAs('docs/evidence/mobile-cover.png');
const bytes = await fs.readFile('docs/evidence/mobile-cover.png');
assert.equal(bytes.readUInt32BE(16), 1600);
assert.equal(bytes.readUInt32BE(20), 2000);
const matchedPixels = await page.evaluate(async ({ original, edited, encoded }) => {
  const load = async src => { const image = new Image(); image.src = src; await image.decode(); return image; };
  const [beforeImage, afterImage, coverImage] = await Promise.all([load(original), load(edited), load(`data:image/png;base64,${encoded}`)]);
  const pixels = (image, width, height) => { const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const c = canvas.getContext('2d'); c.drawImage(image, 0, 0); return c.getImageData(0, 0, width, height).data; };
  const beforeData = pixels(beforeImage, 1200, 650), afterData = pixels(afterImage, 1200, 650), coverData = pixels(coverImage, 1600, 2000);
  let changed = 0, matched = 0;
  for (let y = 355; y < 457; y += 2) for (let x = 430; x < 748; x += 2) {
    const i = (y * 1200 + x) * 4, j = ((540 + Math.round(y * 867 / 650)) * 1600 + Math.round(x * 1600 / 1200)) * 4;
    const difference = Math.abs(beforeData[i] - afterData[i]) + Math.abs(beforeData[i + 1] - afterData[i + 1]) + Math.abs(beforeData[i + 2] - afterData[i + 2]);
    if (difference > 90) { changed++; if (Math.abs(afterData[i] - coverData[j]) + Math.abs(afterData[i + 1] - coverData[j + 1]) + Math.abs(afterData[i + 2] - coverData[j + 2]) < 90) matched++; }
  }
  return { changed, matched };
}, { original: before, edited: after, encoded: bytes.toString('base64') });
assert.ok(matchedPixels.changed > 10 && matchedPixels.matched > 5, `mobile edit should appear on cover: ${JSON.stringify(matchedPixels)}`);
assert.deepEqual(errors, []);
console.log('Mobile Draw, Save, applied car, and cover export passed.');
await browser.close();
