import { launchChrome } from './browser.mjs';
import fs from 'node:fs/promises';

await fs.mkdir('docs/evidence', { recursive: true });
const browser = await launchChrome();
const context = await browser.newContext({ viewport: { width: 1280, height: 720 }, acceptDownloads: true, recordVideo: { dir: 'docs/evidence', size: { width: 1280, height: 720 } } });
const page = await context.newPage();
page.on('pageerror', error => console.log('PAGE ERROR:', error.message));
const caption = async text => page.evaluate(value => {
  let box = document.getElementById('demo-caption');
  if (!box) { box = document.createElement('div'); box.id = 'demo-caption'; Object.assign(box.style, { position: 'fixed', left: '3%', bottom: '3%', zIndex: '99999', background: '#14242ae8', color: '#f5e9d3', borderLeft: '5px solid #ef937a', padding: '12px 18px', font: '800 18px Arial', letterSpacing: '1px', maxWidth: '65%', pointerEvents: 'none' }); document.body.append(box); }
  box.textContent = value;
}, text);
await page.goto(process.env.VICECHROME_URL || 'http://localhost:5173/', { waitUntil: 'networkidle' });
await caption('VICECHROME  /  DESIGN YOUR MARK. OWN THE BOULEVARD.');
await page.waitForTimeout(4500);
await page.getByRole('button', { name: /enter the garage/i }).click();
await caption('01  /  An original illustrated coupe, ready for your panel art');
await page.waitForTimeout(4000);
await page.getByRole('button', { name: /design your panel art/i }).click();
await page.getByText('Draw', { exact: true }).click();
await caption('02  /  Draw a distinctive mark in the real Unlayer Image Editor');
await page.locator('[data-testid="native-draw-size"]').fill('35');
const canvas = await page.locator('canvas.upper-canvas').boundingBox();
await page.mouse.move(canvas.x + canvas.width * .67, canvas.y + canvas.height * .42);
await page.mouse.down();
await page.mouse.move(canvas.x + canvas.width * .81, canvas.y + canvas.height * .63, { steps: 30 });
await page.mouse.up();
await page.waitForTimeout(5000);
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.getByText('ARTWORK APPLIED').waitFor();
await caption('03  /  Save. The same mark now rides on the car.');
await page.waitForTimeout(5000);
await page.getByRole('button', { name: /before \/ after/i }).click();
await page.waitForTimeout(2000);
await page.getByRole('button', { name: /show after/i }).click();
await page.waitForTimeout(2000);
await page.getByRole('button', { name: /roll out/i }).click();
await caption('04  /  ROLL OUT: shutter, light sweep, boulevard');
await page.getByRole('button', { name: /save cover/i }).waitFor({ timeout: 10000 });
await page.waitForFunction(() => !document.querySelector('.cover-actions .primary')?.hasAttribute('disabled'), null, { timeout: 90000 });
await caption('05  /  Export the one-of-one cover');
await page.waitForTimeout(5000);
const download = page.waitForEvent('download', { timeout: 90000 });
await page.getByRole('button', { name: /save cover/i }).click();
const cover = await download;
await cover.saveAs('docs/evidence/demo-cover.png');
await page.waitForTimeout(2200);
const encoded = (await fs.readFile('docs/evidence/demo-cover.png')).toString('base64');
await page.setContent(`<body style="margin:0;background:#14242a;display:flex;align-items:center;justify-content:center;height:100vh"><img src="data:image/png;base64,${encoded}" style="height:100vh;max-width:100%;object-fit:contain"/><div style="position:fixed;left:3%;bottom:3%;background:#14242aee;color:#f5e9d3;border-left:5px solid #ef937a;padding:12px 18px;font:800 18px Arial">THE SAME EDIT  /  ON THE EXPORTED PNG</div></body>`);
await page.waitForTimeout(10000);
const video = await page.video().path();
await context.close();
await browser.close();
console.log(video);
