import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { launchChrome } from './browser.mjs';

await fs.mkdir('docs/evidence', { recursive: true });
const browser = await launchChrome();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(process.env.VICECHROME_URL || 'http://localhost:5173/');
await page.getByRole('button', { name: /enter the garage/i }).click();
await page.getByRole('button', { name: /design your panel art/i }).click();
await page.getByText('Text', { exact: true }).click();
await page.getByText('Heading', { exact: true }).click();
await page.waitForTimeout(500);
const beforeText = await page.locator('canvas.lower-canvas').evaluate(el => el.toDataURL());
const canvasBox = await page.locator('canvas.upper-canvas').boundingBox();
await page.mouse.dblclick(canvasBox.x + 400, canvasBox.y + 260);
assert.equal(await page.evaluate(() => document.activeElement?.tagName), 'TEXTAREA', 'double click should focus the Fabric text editor');
await page.keyboard.press('Control+A');
await page.keyboard.type('TEXT FIT PASS');
await page.keyboard.press('Escape');
const afterText = await page.locator('canvas.lower-canvas').evaluate(el => el.toDataURL());
assert.notEqual(afterText, beforeText, 'editing Heading text must change the canvas');
const geometry = await page.evaluate(() => {
  const frame = document.querySelector('.editor-frame');
  const canvas = frame.querySelector('canvas.upper-canvas');
  const panel = [...frame.querySelectorAll('*')].find(el => {
    const r = el.getBoundingClientRect();
    return r.x > frame.getBoundingClientRect().left + frame.clientWidth * .65 && el.scrollHeight > el.clientHeight + 100 && getComputedStyle(el).overflowY === 'auto' && el.clientHeight > 100;
  });
  const rect = el => el.getBoundingClientRect().toJSON();
  const beforeScroll = panel?.scrollTop ?? -1;
  if (panel) panel.scrollTop = panel.scrollHeight;
  return { frame: rect(frame), wrapper: rect(frame.firstElementChild), canvas: rect(canvas), panel: panel && { client: panel.clientHeight, scroll: panel.scrollHeight, beforeScroll, afterScroll: panel.scrollTop }, buttons: [...frame.querySelectorAll('button')].filter(el => ['Save', 'Cancel'].includes(el.textContent.trim())).map(rect), viewportHeight: innerHeight };
});
assert.ok(geometry.wrapper.bottom <= geometry.frame.bottom + 1, 'SDK wrapper must fit the editor frame');
assert.ok(geometry.canvas.bottom <= geometry.frame.bottom + 1, 'canvas must remain fully visible');
assert.ok(geometry.canvas.height > 300, 'canvas must retain usable height');
assert.ok(geometry.panel?.scroll > geometry.panel?.client && geometry.panel.afterScroll > 0, 'Text settings must scroll inside the editor');
assert.equal(geometry.buttons.length, 2);
assert.ok(geometry.buttons.every(rect => rect.top >= 0 && rect.bottom <= geometry.viewportHeight), 'Save and Cancel must stay visible');
await page.screenshot({ path: 'docs/evidence/editor-text-fixed.png' });
assert.deepEqual(errors, []);
const narrow = await browser.newPage({ viewport: { width: 390, height: 844 } });
await narrow.goto(process.env.VICECHROME_URL || 'http://localhost:5173/');
await narrow.getByRole('button', { name: /enter the garage/i }).click();
await narrow.getByRole('button', { name: /design your panel art/i }).click();
await narrow.getByText('Text', { exact: true }).click();
await narrow.getByText('Heading', { exact: true }).click();
await narrow.locator('.editor-frame').evaluate(el => { el.scrollLeft = 0; });
const mobile = await narrow.evaluate(() => ({ frame: document.querySelector('.editor-frame').getBoundingClientRect().toJSON(), wrapper: document.querySelector('.editor-frame').firstElementChild.getBoundingClientRect().toJSON(), canvas: document.querySelector('canvas.upper-canvas').getBoundingClientRect().toJSON() }));
assert.ok(mobile.wrapper.bottom <= mobile.frame.bottom + 1 && mobile.canvas.bottom <= mobile.frame.bottom + 1);
assert.ok(mobile.canvas.width > 300 && mobile.canvas.height > 300);
assert.ok(await narrow.getByRole('button', { name: /save artwork/i }).isVisible());
await narrow.screenshot({ path: 'docs/evidence/editor-text-mobile-fixed.png' });
console.log('Text → Heading → content edit: desktop and 390 px canvases fit; settings scroll; Save and Cancel visible.');
await browser.close();
